### ISSUE TITLE
[Divers] Optimiser certaines fonctionnalités

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#124]
**Description du problème :**
Certaines fonctionnalités gèlent l'interface du logiciel. Faire en sorte que cela ne soit plus le case.
Voici une liste des fonctionnalités dont les performances doivent être améliorées :
- [x] Test de connexion Internet
- [x] Recherche de mises à jour
- [x] Système de localisation d'IP
