### ISSUE TITLE
[Enhancement] Add the "Connection" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#176]
**Suggestion:**
Add the "Connection" page

**Describe the solution:**

- [x] Add the "Connection" page
    - [x] Add the possibility to check if Internet is available or not
    - [x]  Add the possibility to check if Internet is available or not using a custom website
    - [x] Add the possibility to open the user's web browser
