### ISSUE TITLE
[Enhancement] Add the "Localize IP" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#177]
**Suggestion:**
Add the "Localize IP" page.

**Describe the solution:**

- [x] Add the "Localize IP" page
    - [x] Add the possibility to localize an IP
    - [x] Add the possibility to get the user's current IP
    - [x] Add the possibility to view the location in a Map provider:
        - [x] Google Maps
        - [x] Bing Maps
        - [x] OpenStreetMap
    - [x] Add a message to inform users that InternetTest is using [IP-API](ip-api.com)
