### ISSUE TITLE
[Enhancement] Add the "Down detector" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#178]
**Suggestion:**
Add the "Down detector" page.

**Describe the solution:**

- [x] Add the "Down detector" page
    - [x] Add the possibility to detect if a website is down or not
    - [x] Add a link to this website
    - [x] Add an auto URL formatter (`https://` needed for `WebClient`)
