### ISSUE TITLE
[Enhancement] Add the "Settings" page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#179]
**Suggestion:**
Add the "Settings" page

**Describe the solution:**

- [x] Add the "Settings" page
    - [x] Add the possibility to change language
    - [x] Add the possibility to change theme
    - [x] Add the possibility to see licenses (credit for libraries used)
    - [x] Add the possibility to change the website where the connection is tested
    - [x] Add the possibility to change the default map provider
