### ISSUE TITLE
[Enhancement] Redesign "About" section in settings

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#211]
**Enhancement:**
Redesign "About" section in settings

**Describe the solution:**

- [x] Name of the software
- [x] Version of the software
- [x] Check updates button
- [x] Update options
