### ISSUE TITLE
[Enhancement] Add the possibility to have an historic of connection tests

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#214]
**Suggestion:**
Add the possibility to have an historic of connection tests.

**Describe the solution:**
Add a button which shows:

- [x] When the test was executed
- [x] The result of the test
- [x] The possibility to delete an element
