### ISSUE TITLE
[Enhancement] Add the main window

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#345]
### Enhancement

Add the main window:
 - [x] Possibility to resize the window
 - [x] Mesh gradient background
 - [x] Possibility to maximize the window
 - [x] Possibility to minimize the window
 - [x] Rounded corners
 - [x] Navbar
 - [x] Header
