### ISSUE TITLE
[Enhancement] Add Home page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#346]
### Enhancement

Add Home page.

### Other informations

- [x] "Get started" section _(powered by [Synethia](https://github.com/Leo-Corporation/Synethia))_
- [x] "Suggested actions" section _(powered by [Synethia](https://github.com/Leo-Corporation/Synethia))_
- [x] "Discover" section _(powered by [Synethia](https://github.com/Leo-Corporation/Synethia))_
