### ISSUE TITLE
[Enhancement] Add IP Tools section

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#349]
### Enhancement

Add "IP Tools" section with the following pages: 
- [x] My IP page
- [x] Locate IP page

### Other informations

- [x] IP Tools (section)
  - [x] My IP page
    - [x] "Details" section
   - [x] Locate IP page
      - [x] "Input" section (where the user has to specify the IP)
      - [x] "Details" section (the results and info of the specified IP address)
