### ISSUE TITLE
[Enhancement] Add Settings page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#354]
### Enhancement

Add Settings page with the following settings:
- [x] "About/Updates" section
- [x] "Language" section
- [x] "Theme" section
- [x] "Map provider" section
- [x] "Notifications" section
- [x] "Startup" section
- [x] "Web related settings" section
- [x] "Data" section
