### ISSUE TITLE
[Enhancement] Redesign the home page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#515]
### Enhancement

- [x] Add new Quick Info section with Status, WiFi name, IP Address
- [x] Redesign Page Cards
- [x] Add new Quick Actions system
    - [x] Speed Test
    - [x] Connect to WiFi
    - [x] Recover Passwords
