### ISSUE TITLE
[Enhancement] Add new DownDetector page

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/InternetTest#517]
### Enhancement

- [x] DownDetector page
    - [x] Add "Add website" section
    - [x] Add Website Item with details section
    - [x] Add the possibility to remove a website
    - [x] Add the possibility to test all websites
    - [x] Add new Timer panel
      - [x] Add the possibility to check the status automatically
      - [x] Add the possibility to provide an interval for the auto status check
    - [x] Add the possibility to remember websites
